### ISSUE TITLE
reaching max progress causes small increase in due date

### ISSUE THREAD

**Issue by trafnar** [lo-tp/memory-scheduler#1]
As` progress` increases, the `dueDate` gets pushed further and further in the future (according to `interval`).

However, once you reach `maxProgress`, the due date will only increase by one day. Is that correct?

```javascript
// This condition prevents dueDate from being updated by
// more than one day once maxProgress is reached
if (correct && progress < this.maxProgress) {
    dueDate = now + this.intervals[progress];
}
```

It would have expected that when `maxProgress` is reached, the largest interval size should be used, not the smallest.

Maybe something like this:

```javascript
if (correct) {
    let p = progress > maxProgress ? progress : maxProgress;
    dueDate = now + this.intervals[p];
}
```

Please let me know if I am misunderstanding the code, or the intended algorithm.

**Comment by lo-tp** [comment]
@trafnar 
maxProgress is a threshold. After reaching it, we can say that we have mastered this item.
That is to say, when progress === maxProgress, the item should no longer be studied.

**Comment by trafnar** [comment]
Oh, I understand, thank you!
